"""
Markdown report generator.

Takes an AgentResult and produces a structured penetration test report
in Markdown format — suitable for saving as a file, pasting into a
ticket, or rendering to HTML/PDF in a future phase.
"""

from __future__ import annotations

from datetime import datetime, timezone

from agent.planner import AgentResult


_SEVERITY_EMOJI = {
    "critical": "🔴",
    "high":     "🟠",
    "medium":   "🟡",
    "low":      "🟢",
    "info":     "🔵",
    "unknown":  "⚪",
}


def generate_markdown_report(result: AgentResult, author: str = "RedTeam MCP") -> str:
    """
    Generate a full Markdown pentest report from an AgentResult.

    Returns the report as a string. The caller decides whether to write
    it to a file, return it via MCP, or convert it to HTML/PDF.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []

    # ── Header ────────────────────────────────────────────────────────── #
    lines += [
        "# Penetration Test Report",
        "",
        f"**Generated:** {now}  ",
        f"**Author:** {author}  ",
        f"**Model:** {result.model}  ",
        f"**Goal:** {result.goal}  ",
        f"**Steps Executed:** {result.steps_taken}  ",
        "",
    ]

    # ── Executive Summary ─────────────────────────────────────────────── #
    lines += [
        "## Executive Summary",
        "",
        result.final_summary,
        "",
    ]

    # ── Aggregated Findings ───────────────────────────────────────────── #
    all_ports:  list[str] = []
    all_subs:   list[str] = []
    all_vulns:  list[str] = []

    for step in result.steps:
        all_ports  += step.found_ports
        all_subs   += step.found_subdomains
        all_vulns  += step.found_vulns

    # Deduplicate
    all_ports = list(dict.fromkeys(all_ports))
    all_subs  = list(dict.fromkeys(all_subs))
    all_vulns = list(dict.fromkeys(all_vulns))

    if all_ports:
        lines += ["## Open Ports", ""]
        for p in all_ports:
            lines.append(f"- `{p}`")
        lines.append("")

    if all_subs:
        lines += ["## Discovered Subdomains", ""]
        for s in all_subs:
            lines.append(f"- `{s}`")
        lines.append("")

    if all_vulns:
        lines += ["## Vulnerabilities & Findings", ""]
        for v in all_vulns:
            # Try to extract severity prefix like [HIGH]
            sev = "unknown"
            for s in _SEVERITY_EMOJI:
                if f"[{s.upper()}]" in v.upper():
                    sev = s
                    break
            emoji = _SEVERITY_EMOJI.get(sev, "⚪")
            lines.append(f"- {emoji} {v}")
        lines.append("")

    # ── Step-by-Step Evidence ─────────────────────────────────────────── #
    lines += ["## Step-by-Step Evidence", ""]

    for step in result.steps:
        tc = step.tool_call
        lines += [
            f"### Step {step.step} — `{tc.tool}`",
            "",
            f"**Reason:** {tc.reason}  ",
        ]
        if tc.args:
            lines.append("**Arguments:**")
            for k, v in tc.args.items():
                lines.append(f"- `{k}`: `{v}`")
        lines += [
            "",
            "**Summary:**",
            f"> {step.summary}",
            "",
        ]
        if step.found_ports:
            lines += ["**Ports found:**"]
            for p in step.found_ports:
                lines.append(f"- `{p}`")
            lines.append("")
        if step.found_subdomains:
            lines += ["**Subdomains found:**"]
            for s in step.found_subdomains[:20]:
                lines.append(f"- `{s}`")
            if len(step.found_subdomains) > 20:
                lines.append(f"- *(+{len(step.found_subdomains) - 20} more)*")
            lines.append("")
        if step.found_vulns:
            lines += ["**Findings:**"]
            for v in step.found_vulns:
                lines.append(f"- {v}")
            lines.append("")

    # ── Footer ─────────────────────────────────────────────────────────── #
    lines += [
        "---",
        "*Generated by RedTeam MCP — for authorised use only.*",
    ]

    return "\n".join(lines)
